
			var mychart = echarts.init(document.getElementById("main"));
			mychart.setOption({
				title:{
					text:'新增用户统计图',
					subtext:'纯属虚构',
					left:'center',
					textStyle:{
						color:'#666'
					}
				},
				legend:{
					right:'right',
					width:500,
					itemWidth:40,
					data:[
					   {name:'新增用户'}
					],
					textStyle:{
						color:'#d7d7d7'
					}
				},
				xAxis:[
				   {
				   	type:'category',
				   	axisTick:{
				   		show:false
				   	},
				   	data:[]
				   }
				],
				yAxis:{
					"axisLine":{
						lineStyle:{
							color:'#c0576d'
						}
					},
					splitLine:{
						show:true,
						lineStyle:{
							color:'#c0576d'
						}
					},
					"axisTick":{
						'show':false
					},
					axisLabel:{
						textStyle:{
							color:'#ffd285'
						}
					},
					type:'value'
				},
				tooltip:{
					trigger:'axis',
					axisPointer:{
						type:'shadow'
					}
				},
				toolbox:{
					orient:'vertical',
					right:'right',
					top:'center',
					show:true,
					feature:{
						dataZoom:{
							yAxisIndex:'none'
						},
						dataView:{readOnly:false},
						magicType:{type:['line','bar']},
						restore:{},
						saveAsImage:{}
					}
				},
				series:[
				   {
				   	 name:'新增用户',
				   	 type:'bar',
				   	 barWidth:20,
				   	 itemStyle:{
				   	 	normal:{
				   	 		barBorderRadius:10,
				   	 		color:'#ffd285'
				   	 	}
				   	 },
				   	 data:[]
				   }
				]
			});
			var day = [];
			var num = [];
			function getData(){
				$.ajax({
					type:"post",
					url:"mysql/addpreson.php",
					async:true,
					data:{},
					dataType:'json',
					success:function(result){
						if(result){
							for(var i = 0;i < result.length;i ++){
								day.push(result[i].day);
							}
							for(var i = 0;i < result.length;i++){
								num.push(result[i].num);
							}
						}
						mychart.setOption({
							xAxis:{
								data:day
							},
							series:[
							  {
							  	data:num
							  }
							]
						})
					}
				});
			}
			getData();